-- Benutzer

create table benutzer
(
    benutzer_id                 number generated by default as identity
                                constraint pk_benutzer primary key,
    nutzername                  varchar2(50)     not null,
    email                       varchar2(255)    not null,
    passwort_hash               varchar2(255)    not null,
    registriert_am              date            default sysdate not null,
    anzeige_name                varchar2(100),
    avatar_url                  varchar2(4000),
    bevorzugte_schwierigkeit    varchar2(20),
    
    constraint uq_benutzer_nutzername   unique (nutzername),
    constraint uq_benutzer_email        unique (email)
);

--------------------------------------------------------------------------

-- Level (inklusive Song-Infos)

create table spiellevel 
(
    level_id                number generated by default as identity
                            constraint pk_spiellevel primary key,
    name                    varchar2(100)   not null,
    schwierigkeitsgrad      varchar2(20),
    ist_roguelike           char(1)         default 'N' not null, -- 'J' oder 'N'
    beschreibung            varchar2(1000),
    song_titel              varchar2(200)   not null,
    song_dateipfad          varchar2(4000)  not null,
    bpm                     number(4),
    dauer_sekunden          number(6),
    
    constraint ck_spiellevel_ist_roguelike check (ist_roguelike in ('J','N'))
);

--------------------------------------------------------------------------

-- Spielrunde (GAME SESSION)

create table spielrunde
(
    runde_id            number generated by default as identity
                        constraint pk_spielrunde primary key,
    benutzer_id         number not null,
    level_id            number not null,
    startzeit           timestamp default systimestamp not null,
    endzeit             timestamp,
    gesamtpunkte        number(10),
    trefferquote        number(5,2),    -- z.B. 98.50 (%)
    max_combo           number(5),
    anzahl_miss         number(5),
    
    constraint fk_spielrunde_benutzer
        foreign key (benutzer_id) references benutzer (benutzer_id),
    constraint fk_spielrunde_level
        foreign key (level_id) references spiellevel (level_id)
);

--------------------------------------------------------------------------

-- Indexe auf Fremdschlüssel (Performance)

create index idx_spielrunde_benutzer
    on spielrunde (benutzer_id);
    
create index idx_spielrunde_level
    on spielrunde (level_id);
    
--------------------------------------------------------------------------

/*
drop table benutzer;
drop table spiellevel;
drop table spielrunde;
drop index idx_spielrunde_benutzer;
drop index idx_spielrunde_level;
*/
